- src: git+https://github.com/geerlingguy/ansible-role-docker.git
  version: "2.1.0"
  name: docker

- src: git+https://github.com/geerlingguy/ansible-role-clamav.git
  version: "1.2.2"
  name: clamav